#! /bin/bash
# Copyright 2020 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
set -e

PATH=${PATH}:${APPDIR}/bin
export PATH=${PATH}

LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${APPDIR}/lib
LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${APPDIR}/lib64
LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${APPDIR}/lib64/qt5
LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${APPDIR}/lib64/vdpau
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}

XDG_DATA_HOME=${XDG_DATA_HOME}:${APPDIR}/share
export XDG_DATA_HOME=${XDG_DATA_HOME}

QT_DEBUG_PLUGINS=1
export QT_DEBUG_PLUGINS

cd ${OWD}

# exec ${APPDIR}/bin/smplayer -skin default $@
exec ${APPDIR}/bin/smplayer $@
